//DEALER PORTAL
#include<iostream.h>
#include<conio.h>
void kerala()
{
 clrscr();
 cout<<"\n\n\n\t\t\t 1. GROGET KOZHIKODE \n";
 cout<<"\n\t\t\t\t NH 17, Calicut Kannur Highway Puthiyangadi, ";
 cout<<"\n\t\t\t\t P.O., Pavanagad, ";
 cout<<"\n\t\t\t\t Kozhikode. ";
 cout<<"\n\t\t\t\t Kerala(KL) ";
 cout<<"\n\t\t\t\t Phone: 0495 662 5555 ";


 cout<<"\n\n\n\t\t\t 2.KUN EXCLUSIVE \n";
 cout<<"\n\t\t\t\t NH 47,Cochin-Coimbatore Highway, ";
 cout<<"\n\t\t\t\t P.O.Nurani, ";
 cout<<"\n\t\t\t\t Palakkad. ";
 cout<<"\n\t\t\t\t Kerala(KL) ";
 cout<<"\n\t\t\t\t Phone: 0495 253 5555 ";
}

void tamilnadu()
{
 clrscr();
 cout<<"\n\n\n\t 1. GROGET COIMBATORE \t\t 2. PRAHASU GROGET";
 cout<<"\n";
 cout<<"\n\t       Near Nehru Stadium   \t\t Anna Salai,Nandanam 535";
 cout<<"\n\t       Coimbatore,          \t\t Chennai,";
 cout<<"\n\t       Tamil Nadu(TN).      \t\t Tamil Nadu(TN).";
 cout<<"\n\t       Phone: 0422 403 0100 \t\t Phone: 044 4560 0456";



 cout<<"\n\n\n\n\t 3. SAFETY GROGET     \t\t 4.  ANAAMALAIS GROGET";
 cout<<"\n";
 cout<<"\n\t       10/525, NH-47,       \t\t S.F.No 696/4,Badhmini Garden,";
 cout<<"\n\t       Solipalayam ,        \t\t Kangayam Rd,";
 cout<<"\n\t       Perundurai,Erode.    \t\t Tirupur.";
 cout<<"\n\t       Tamil Nadu(TN).      \t\t Tamil Nadu(TN).";
 cout<<"\n\t       Phone: 9842322499    \t\t Phone:0421-228899";


}

void karnataka()
{
 clrscr();
 cout<<"\n\n\n\t\t\t 1. GROGET BENGALURU \n";
 cout<<"\n\t\t\t\t Survey No. 6/1, ";
 cout<<"\n\t\t\t\t Beratana Agrahara Hosur Main Road, ";
 cout<<"\n\t\t\t\t Electronic City P.O ";
 cout<<"\n\t\t\t\t Bengaluru, ";
 cout<<"\n\t\t\t\t Karnataka(KA). ";
 cout<<"\n\t\t\t\t Phone: 080 4517 0000 ";

 cout<<"\n\n\n\n\t\t\t 2. GROGET KOLAR \n";
 cout<<"\n\t\t\t\t 66/32,ASHOK NAGAR  ";
 cout<<"\n\t\t\t\t KOLAR, ";
 cout<<"\n\t\t\t\t KARNATAKA (KA) ";
 cout<<"\n\t\t\t\t Phone:9986234286 ";
}

void rajasthan()
{
 clrscr();
 cout<<"\n\n\n\t\t\t 1. HSP GROGET \n";
 cout<<"\n\t\t\t\t Goverdhan Villas Ahmedabad Road ";
 cout<<"\n\t\t\t\t Udaipur, ";
 cout<<"\n\t\t\t\t Rajasthan(RJ). ";
 cout<<"\n\t\t\t\t Phone: 0294 248 1357 ";

 cout<<"\n\n\n\t\t\t 2. GRANDEUR GROGET \n";
 cout<<"\n\t\t\t\t Tuwariyan Ki Dhani ";
 cout<<"\n\t\t\t\t Vidhani, ";
 cout<<"\n\t\t\t\t Rajasthan(RJ). ";
 cout<<"\n\t\t\t\t Phone: 0294 545 1357 ";
}

void jharkhand()
{
 clrscr();
 cout<<"\n\n\n\t\t\t 1. SUPRAHA GROGET \n";
 cout<<"\n\t\t\t\t Kanta Tolli Chowk, ";
 cout<<"\n\t\t\t\t PS Purulia Road ";
 cout<<"\n\t\t\t\t Ranchi, ";
 cout<<"\n\t\t\t\t Jharkhand(JH). ";
 cout<<"\n\t\t\t\t Phone: 077658 16666 ";


 cout<<"\n\n\n\t\t\t 2. MD GROGET \n";
 cout<<"\n\t\t\t\t PN 1 P Medium Sector, ";
 cout<<"\n\t\t\t\t RIT Modh ";
 cout<<"\n\t\t\t\t Jamshedpur, ";
 cout<<"\n\t\t\t\t Jharkhand(JH). ";
 cout<<"\n\t\t\t\t Phone: 077658 15555 ";
}

void maharashtra()
{
 clrscr();
 cout<<"\n\n\n\t\t\t 1. GROGET KOLHAPUR \n";
 cout<<"\n\t\t\t\t 1565/B C ,Mahadwar Rd ";
 cout<<"\n\t\t\t\t Ichalkaranji ";
 cout<<"\n\t\t\t\t Maharashtra (MH) ";
 cout<<"\n\t\t\t\t Phone:9942413999 ";

 cout<<"\n\n\n\t\t\t 2. GROGET NASHIK  \n";
 cout<<"\n\t\t\t\t Lokmat Bhavan ";
 cout<<"\n\t\t\t\t Mumai Agra Highway ";
 cout<<"\n\t\t\t\t Maharashtra (MH) ";
 cout<<"\n\t\t\t\t Phone:9255525835 ";


}

void gujarat()
{
 clrscr();
 cout<<"\n\n\n\t\t\t 1. GROGET SURAT \n";
 cout<<"\n\t\t\t\t 520,Sector C ,Katagram rd, ";
 cout<<"\n\t\t\t\t Surat , ";
 cout<<"\n\t\t\t\t Gujarat(GJ) ";
 cout<<"\n\t\t\t\t Phone:9894525215 ";

 cout<<"\n\n\n\n\t\t\t 2. BENCHMARK CARS \n";
 cout<<"\n\t\t\t\t Sun court, Near Sola Flyover,  ";
 cout<<"\n\t\t\t\t S.G. Road, Sola, ";
 cout<<"\n\t\t\t\t Ahmedabad,  ";
 cout<<"\n\t\t\t\t Gujarat (GJ) ";
 cout<<"\n\t\t\t\t Phone: 80009 62000 ";
}

void bihar()
{
 clrscr();
 cout<<"\n\n\n\t\t\t 1. GROGET CHAMPARAN \n";
 cout<<"\n\t\t\t\t 10/15,NH 104, ";
 cout<<"\n\t\t\t\t Champaran,Tirhut, ";
 cout<<"\n\t\t\t\t Bihar.(BR) ";
 cout<<"\n\t\t\t\t Phone:9571596542 ";

 cout<<"\n\n\n\t\t\t 2. GROGET YAJUAR \n";
 cout<<"\n\t\t\t\t 696/32,Ashiana Vihar Apartment,  ";
 cout<<"\n\t\t\t\t Patna ";
 cout<<"\n\t\t\t\t Bihar.(BR) ";
 cout<<"\n\t\t\t\t Phone:9571595454 ";
}

void telangana()
{
 clrscr();
 cout<<"\n\n\n\t\t\t 1. SUNDARAM MOTORS \n";
 cout<<"\n\t\t\t\t 6-3-563/A, Erramanzil Colony,  ";
 cout<<"\n\t\t\t\t Banjara Hills Road, ";
 cout<<"\n\t\t\t\t Somajiguda,  ";
 cout<<"\n\t\t\t\t Hyderabad, ";
 cout<<"\n\t\t\t\t Telangana (TS). ";
 cout<<"\n\t\t\t\t Phone:9879878996 ";

 cout<<"\n\n\n\t\t\t 2.GROGET GACHIBOWLI \n";
 cout<<"\n\t\t\t\t 7-56/19, Dargah Road ,  ";
 cout<<"\n\t\t\t\t Radhe Nagar, ";
 cout<<"\n\t\t\t\t Gachi Bowli,Rai Du,  ";
 cout<<"\n\t\t\t\t Hyderabad, ";
 cout<<"\n\t\t\t\t Telangana (TS). ";
 cout<<"\n\t\t\t\t Phone:9879545448 ";
}
void main()
{
int state;
clrscr();
textcolor(11);
textbackground(9);

cout<<"\n \n \t\t      13 GROGETTERS OVER INDIA!!!";
cout<<"\n \n\n \t1.Kerala \n \t2.Tamil Nadu \n \t3.Karnataka \n \t4.Rajasthan \n \t5.Maharashtra";
cout<<"\n \t6.Gujarat \n \t7.Jharkhand \n \t8.Bihar \n \t9.Telangana ";
cout<<"\n \n\tSelect Your State:";
cin>>state;
 switch(state)
 {
 case 1:
	kerala();
	break;
 case 2:
	tamilnadu();
	break;
 case 3:
	karnataka();
	break;
 case 4:
	rajasthan();
	break;
 case 5:
	maharashtra();
	break;
 case 6:
	gujarat();
	break;
 case 7:
	jharkhand();
	break;
 case 8:
	bihar();
	break;
 case 9:
	telangana();
	break;

 default:
       cout<<"\n SORRY!!!NO GROGRETTERS ARE AVAILABLE ";
       break;
 }

getch();
}